### ISSUE TITLE
Scheduled Activity on Twitter does not work

### ISSUE THREAD

**Issue by jkoenig** [CampaignChain/campaignchain-ce#6]
A scheduled 'update status' activity on twitter channel does not post something to the actual twitter channel.

**Comment by groganz** [comment]
Would be great if you could do some debugging to provide more details on what doesn't work. The relevant code is https://github.com/CampaignChain/core/blob/master/Command/SchedulerCommand.php, which coordinates jobs that then are being executed through https://github.com/CampaignChain/core/blob/master/Command/JobCommand.php.

**Comment by jkoenig** [comment]
Here is the stack trace:
```
php.EMERGENCY: Fatal Error: Uncaught exception 'Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException' with message 'The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.' in /var/www/campaignchain/app/cache/prod/classes.php:3290 Stack trace: #0 /var/www/campaignchain/app/cache/prod/classes.php(3028): Symfony\Component\Security\Core\Authorization\AuthorizationChecker->isGranted('IS_AUTHENTICATE...', NULL) #1 /var/www/campaignchain/vendor/campaignchain/core/EventListener/LoginListener.php(52): Symfony\Component\Security\Core\SecurityContext->isGranted('IS_AUTHENTICATE...') #2 [internal function]: CampaignChain\CoreBundle\EventListener\LoginListener->setLocale(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #3 /var/www/campaignchain/app/cache/prod/classes.php(2193): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\Ge {"type":1,"file":"/var/www/campaignchain/app/cache/prod/classes.php","line":3290,"level":22527,"stack":[]} []
```

**Comment by groganz** [comment]
What's the output if you run

    php app/console campaignchain:scheduler

?

**Comment by jkoenig** [comment]
Scheduler ID: 72072
Interval: 9600 minute(s)
Period starts: 2015-05-29 21:06:21 UTC
Period ends: 2015-06-05 13:06:21 UTC
No actions of type "operation" scheduled within the past 9600 minutes.
No actions of type "activity" scheduled within the past 9600 minutes.
No actions of type "milestone" scheduled within the past 9600 minutes.
No actions of type "campaign" scheduled within the past 9600 minutes.
No scheduled Operation reports.
Duration of scheduler: 367 milliseconds

**Comment by groganz** [comment]
Works for me :)

Try the following:

0. Turn off the cron job for the scheduler in case you have it configured.
1. Configure your timezone in CampaignChain at /profile/edit (this is not mandatory, it's just for you so that you don't get confused by timezone differences)
2. Create a Twitter activity and schedule it 5 minutes from now.
3. 1 minute after the activity was supposed, execute this command in the root of CampaignChain:
php app/console campaignchain:scheduler

If it works as expected, you should see an output that includes lines such as:
- These actions of type "operation"  will be executed:
- Executing jobs now:
 1/1 [============================] 100%

Hope this helps.

**Comment by groganz** [comment]
@jkoenig Any success?
