### ISSUE TITLE
Installation on Windows - RuntimeException

### ISSUE THREAD

**Issue by korzo** [CampaignChain/campaignchain-ce#9]
Installation on Windows fails with message:

``` 
[Symfony\Component\Process\Exception\RuntimeException]
  TTY mode is not supported on Windows platform.

Script Sp\BowerBundle\Composer\ScriptHandler::bowerInstall handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the ""sp:bower:install --interactive=false"" command.
```
See: https://github.com/symfony/Process/blob/master/Process.php#L948

**Comment by groganz** [comment]
At which point during the installation did you encounter this issue?

**Comment by korzo** [comment]
I believe it was when I ran 
```
php app/console assetic:dump --env=prod --no-debug
```
Shipped version of yuicompressor doesn't work on Windows(java.io.FileNotFoundException). I had to replace it with yuicompressor-2.4.7.

After installation all paths in app\config\campaignchain_bundles.yml are prefixed with ..\..\ 
e.g.
```
    - { resource: '..\..\C:\wamp\www\campaignchain\vendor\campaignchain\operation-twitter\Resources\config\config.yml' }
```
After php app/console cache:clear --env=prod --no-debug I've got error
```                                                                    
  [Symfony\Component\Config\Definition\Exception\ForbiddenOverwriteException]                           Configuration path "fos_user.db_driver" cannot be overwritten.    
                                                                    
  You have to define all options for this path, and any of its sub-paths in one configuration section.
```
and it was the point I gave up.

**Comment by groganz** [comment]
Back from vacation. Thanks for reporting the details!

I've just tested installation on Windows 7:

The error with the wrong path in campaignchain_bundles.yml has just been fixed in dev-master.

yuicompressor-2.4.8 actually worked for me on Windows 7 with Java  8.0.

As for the "TTY mode is not supported on Windows platform." error, I've pushed a fix to the SpBower project. Until it got accepted, please try this workaround with the latest dev-master branch of campaignchain-ce:

1. Install campaignchain-ce from scratch.
2. Once you see the above TTY error, go to  [path to campaignchain-ce]\vendor\sp\bower-bundle\Bower\Bower.php and apply this fix: https://github.com/Spea/SpBowerBundle/pull/131/files
3. Run this command in the campaignchain-ce root: composer run post-install-cmd

**Comment by groganz** [comment]
The fix for SpBower was merged. Hence, you can skip the workaround and simply install campaignchain-ce as usual.
